[build]
  publish = "/"

# Corrected redirect rules
[[redirects]]
  from = "privacy.corneroom.co.za"
  to = "cornerroom.co.za/privacy"
  status = 301

[[redirects]]
  from = "/privacy/*"
  to = "/:splat"
  status = 200
