[build]
  publish = "/"

# Corrected redirect rules
[[redirects]]
  from = "https://privacy.corneroom.co.za"
  to = "https://cornerroom.co.za/privacy"
  status = 301

[[redirects]]
  from = "/privacy/*"
  to = "/:splat"
  status = 200
